services:
  - type: web
    name: mcne1
    runtime: python
    buildCommand: pip install -r requirements-server.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
